package com.github.historybuilder.git;

import com.github.historybuilder.model.Commit;
import com.github.historybuilder.config.HistoryConfig;
import org.eclipse.jgit.api.Git;
import org.eclipse.jgit.api.errors.GitAPIException;
import org.eclipse.jgit.lib.PersonIdent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * Manages Git repository operations.
 */
public class GitRepositoryManager {
    private static final Logger logger = LoggerFactory.getLogger(GitRepositoryManager.class);
    private Git git;
    private File repoDir;

    /**
     * Initializes a new Git repository at the specified path.
     */
    public void initializeRepository(HistoryConfig config) throws IOException, GitAPIException {
        repoDir = new File(config.getRepositoryPath());

        // Create directory if it doesn't exist
        if (!repoDir.exists()) {
            if (!repoDir.mkdirs()) {
                throw new IOException("Failed to create repository directory: " + config.getRepositoryPath());
            }
        }

        // Initialize git repository
        git = Git.init().setDirectory(repoDir).call();

        // Configure user
        var config_obj = git.getRepository().getConfig();
        config_obj.setString("user", null, "name", config.getAuthorName());
        config_obj.setString("user", null, "email", config.getAuthorEmail());
        config_obj.save();

        logger.info("Initialized Git repository at: {}", repoDir.getAbsolutePath());

        // Create initial commit
        createInitialCommit(config);
    }

    /**
     * Creates the initial commit with README.
     */
    private void createInitialCommit(HistoryConfig config) throws IOException, GitAPIException {
        File readmeFile = new File(repoDir, "README.md");
        String readmeContent = "# GitHub Contribution History\n\n" +
                "This repository contains generated contribution history.\n" +
                "Generated by GitHub History Builder\n";

        Files.write(readmeFile.toPath(), readmeContent.getBytes());

        git.add().addFilepattern("README.md").call();

        PersonIdent author = new PersonIdent(config.getAuthorName(), config.getAuthorEmail());
        git.commit()
                .setMessage("Initial commit")
                .setAuthor(author)
                .setCommitter(author)
                .call();

        logger.info("Created initial commit with README");
    }

    /**
     * Writes a commit to the repository.
     */
    public void writeCommit(Commit commit) throws IOException, GitAPIException {
        if (git == null) {
            throw new IllegalStateException("Repository not initialized. Call initializeRepository first.");
        }

        // Write file content
        Path filePath = Paths.get(repoDir.getAbsolutePath(), commit.getFilePath());
        Files.createDirectories(filePath.getParent());

        if (Files.exists(filePath)) {
            // Append to existing file
            String currentContent = new String(Files.readAllBytes(filePath));
            Files.write(filePath, (currentContent + commit.getFileContent()).getBytes());
        } else {
            // Create new file
            Files.write(filePath, commit.getFileContent().getBytes());
        }

        // Stage the file
        git.add().addFilepattern(commit.getFilePath()).call();

        // Create commit
        PersonIdent author = new PersonIdent(
                commit.getAuthor().getName(),
                commit.getAuthor().getEmail(),
                commit.getTimestamp().toInstant().toEpochMilli(),
                commit.getTimestamp().getOffset().getTotalSeconds() / 60
        );

        git.commit()
                .setMessage(commit.getMessage())
                .setAuthor(author)
                .setCommitter(author)
                .call();
    }

    /**
     * Writes multiple commits to the repository.
     */
    public void writeCommits(List<Commit> commits) throws IOException, GitAPIException {
        logger.info("Writing {} commits to repository...", commits.size());

        int progress = 0;
        for (Commit commit : commits) {
            writeCommit(commit);
            progress++;

            if (progress % 100 == 0) {
                logger.info("Progress: {}/{} commits written", progress, commits.size());
            }
        }

        logger.info("All {} commits written successfully", commits.size());
    }

    /**
     * Closes the repository.
     */
    public void close() {
        if (git != null) {
            git.close();
        }
    }

    /**
     * Gets the repository directory.
     */
    public File getRepositoryDirectory() {
        return repoDir;
    }
}

